name: Test contracts
on:
    push:
        branches: ['*']
    pull_request:
        branches: [main]

jobs:
    test-sol-contracts:
        name: Test solidity contracts
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install dependencies
              run: yarn install
            - name: Build
              run: yarn build
            - name: Lint
              run: yarn lint
            - name: Run tests
              run: yarn test
    build-test-go-executables:
        name: Build and test go executables
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: GO
              uses: actions/setup-go@v2
              with:
                  go-version: '^1.17'
            
