name: Generates files from contract
on:
    push:
        branches: [main]

jobs:
    generate-files:
        runs-on: ubuntu-latest
        timeout-minutes: 8
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: GO
              uses: actions/setup-go@v2
              with:
                  go-version: '^1.17'
            - name: Install Go-ethereum
              run: |
                  echo "Installing Go-ethereum..."
                  sudo add-apt-repository -y ppa:ethereum/ethereum
                  sudo apt-get update
                  sudo apt-get install ethereum
                  echo "Go-ethereum installed!"
            - name: Install dependencies
              run: yarn install
            - name: Download a previous gas-report
              uses: actions/download-artifact@v3.0.1
              with:
                name: gas-report
            - name: Run tests
              run: yarn test
            - name: Archive gas-report results
              uses: actions/upload-artifact@v3
              with:
                  name: gas-report
                  path: gasReport.txt
            - name: Run difference calculator
              run: yarn gas-diff
            - name: Archive gas-report difference results
              uses: actions/upload-artifact@v3
              with:
                name: gas-report-difference
                path: gasReportDiff.txt
            - name: Generate addresses package into ./gethApi/go
              run: yarn generate
            - name: Format generated package
              working-directory: ./gethApi/go/addresses
              run: go fmt addresses.go
            - name: Generate .go files into ./gethApi/go
              run: yarn compile:bin
            - name: Go mod init
              working-directory: ./gethApi/go
              run: go mod init github.com/distroenergy/gethApi-generated
            - name: Go mod tidy
              working-directory: ./gethApi/go
              run: go mod tidy
            - name: Go build
              working-directory: ./gethApi/go
              run: go build ./...
            - name: Generate and deploy to abigen repo
              uses: tagus/git-deploy@v0.3.2
              with:
                  changes: gethApi/go
                  repository: git@github.com:distroenergy/gethApi-generated.git
                  ssh_key: ${{ secrets.DISTRO_GITHUB_CHAIN_GEN_DEPLOY_KEY }}
                  name: anthonyoliai
                  email: anthony@distroenergy.com
