name: Generates files from contract
on:
    push:
        branches: [master]

jobs:
    generate-files:
        runs-on: ubuntu-latest
        timeout-minutes: 8
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: GO
              uses: actions/setup-go@v2
              with:
                  go-version: '^1.17'
            - name: Install Go-ethereum
              run: |
                  echo "Installing Go-ethereum..."
                  sudo add-apt-repository -y ppa:ethereum/ethereum
                  sudo apt-get update
                  sudo apt-get install ethereum
                  echo "Go-ethereum installed!"
            - name: Install dependencies
              run: yarn install
            - name: Download a previous gas-report
              id: download-artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                github_token: ${{secrets.GITHUB_TOKEN}}
                workflow_conclusion: success
                branch: master
                name: gas-report
            - name: check download by ls
              run: ls
            - name: Rename to oldGasReport
              run: mv gasReport.txt oldGasReport.txt
            - name: Run tests
              run: yarn test
            - name: Archive gas-report results
              uses: actions/upload-artifact@v3
              with:
                  name: gas-report
                  path: gasReport.txt
            - name: Run difference calculator
              run: yarn gas-diff
            - name: Archive gas-report difference results
              uses: actions/upload-artifact@v3
              with:
                name: gas-report-difference
                path: gasReportDiff.txt
